name: Build & Deploy
concurrency: ci-${{ github.ref }}
permissions:
  contents: write
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean-exclude: pr-preview
          force: false
