on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.29.1-focal
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx playwright test
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'results.xml'
